#ifndef RTT_SPGEMM_DMMA_TILE_TAIL_QUEUE_H_
#define RTT_SPGEMM_DMMA_TILE_TAIL_QUEUE_H_

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <vector>

/*
 * CPU proof oracle for the default-off tile-tail-queue scheduler.
 *
 * Production admission is generated by exact symbolic on the GPU.  Keeping
 * this small host mirror gives tests and offline structure tools one precise
 * definition of the policy without copying C values or a dense task-cost
 * array to the CPU.  A task remains an ordinary one-warp C-tile task unless
 * its exact K-list merge work is above admission_threshold.
 */
struct DmmaTileTailQueueCostModel
{
    double intercept = 0.0;
    double scan = 1.0;
    double match = 8.0;
    double output = 0.25;
};

struct DmmaTileTailQueuePolicy
{
    bool enabled = false;
    double admission_threshold = 256.0;
    double chunk_target = 256.0;
    int max_chunks = 8;
    double max_heavy_fraction = 0.01;
    int record_capacity = 1 << 20;
    std::size_t workspace_limit_bytes =
        std::size_t(1024) * 1024 * 1024;
    bool workspace_reduction = true;
};

struct DmmaTileTailQueueExactTask
{
    int task = -1;
    int scans = 0;
    int matches = 0;
    int output_nnz = 0;
};

struct DmmaTileTailQueueTaskPlan
{
    int task = -1;
    int scans = 0;
    int matches = 0;
    int output_nnz = 0;
    int chunks = 0;
    double splittable_work = 0.0;
    double full_work = 0.0;
};

enum DmmaTileTailQueueGateReason
{
    DMMA_TILE_TAIL_QUEUE_DEFAULT_OFF = 0,
    DMMA_TILE_TAIL_QUEUE_ENABLED = 1,
    DMMA_TILE_TAIL_QUEUE_INVALID_POLICY = 2,
    DMMA_TILE_TAIL_QUEUE_INVALID_TASK = 3,
    DMMA_TILE_TAIL_QUEUE_ZERO_HEAVY = 4,
    DMMA_TILE_TAIL_QUEUE_RECORD_CAPACITY = 5,
    DMMA_TILE_TAIL_QUEUE_HEAVY_FRACTION = 6,
    DMMA_TILE_TAIL_QUEUE_WORKSPACE_CAPACITY = 7,
    DMMA_TILE_TAIL_QUEUE_CHUNK_OVERFLOW = 8
};

static inline const char *dmma_tile_tail_queue_gate_reason_name(
    DmmaTileTailQueueGateReason reason)
{
    switch (reason)
    {
    case DMMA_TILE_TAIL_QUEUE_ENABLED:
        return "enabled";
    case DMMA_TILE_TAIL_QUEUE_INVALID_POLICY:
        return "invalid-policy";
    case DMMA_TILE_TAIL_QUEUE_INVALID_TASK:
        return "invalid-task";
    case DMMA_TILE_TAIL_QUEUE_ZERO_HEAVY:
        return "zero-heavy";
    case DMMA_TILE_TAIL_QUEUE_RECORD_CAPACITY:
        return "record-capacity";
    case DMMA_TILE_TAIL_QUEUE_HEAVY_FRACTION:
        return "heavy-fraction";
    case DMMA_TILE_TAIL_QUEUE_WORKSPACE_CAPACITY:
        return "workspace-capacity";
    case DMMA_TILE_TAIL_QUEUE_CHUNK_OVERFLOW:
        return "chunk-overflow";
    default:
        return "default-off";
    }
}

struct DmmaTileTailQueuePlan
{
    DmmaTileTailQueueGateReason reason =
        DMMA_TILE_TAIL_QUEUE_DEFAULT_OFF;
    std::size_t output_tasks = 0;
    std::size_t ordinary_tasks = 0;
    std::size_t heavy_tasks = 0;
    std::size_t chunks = 0;
    std::size_t descriptor_bytes = 0;
    std::size_t heavy_flag_bytes = 0;
    std::size_t partial_workspace_bytes = 0;
    double heavy_fraction = 0.0;
    double average_chunks = 0.0;
    std::vector<DmmaTileTailQueueTaskPlan> heavy;
};

/* Invalid or incomplete sparse metadata cannot describe an effective split
 * plan.  Reset every derived field to the direct exactly-once partition while
 * preserving output_tasks and the failure reason selected by the caller. */
static inline void dmma_tile_tail_queue_reset_incomplete_plan(
    DmmaTileTailQueuePlan *plan)
{
    if (plan == nullptr)
        return;
    plan->ordinary_tasks = plan->output_tasks;
    plan->heavy_tasks = 0;
    plan->chunks = 0;
    plan->descriptor_bytes = 0;
    plan->heavy_flag_bytes = 0;
    plan->partial_workspace_bytes = 0;
    plan->heavy_fraction = 0.0;
    plan->average_chunks = 0.0;
    plan->heavy.clear();
}

static inline bool dmma_tile_tail_queue_policy_valid(
    const DmmaTileTailQueuePolicy &policy,
    const DmmaTileTailQueueCostModel &model)
{
    return std::isfinite(policy.admission_threshold) &&
           policy.admission_threshold > 0.0 &&
           std::isfinite(policy.chunk_target) && policy.chunk_target > 0.0 &&
           policy.max_chunks >= 2 && policy.max_chunks <= 32 &&
           std::isfinite(policy.max_heavy_fraction) &&
           policy.max_heavy_fraction >= 0.0 &&
           policy.max_heavy_fraction <= 1.0 &&
           policy.record_capacity > 0 && std::isfinite(model.intercept) &&
           model.intercept >= 0.0 && std::isfinite(model.scan) &&
           model.scan >= 0.0 && std::isfinite(model.match) &&
           model.match >= 0.0 && std::isfinite(model.output) &&
           model.output >= 0.0;
}

/* Match dmma_tail_chunk_count_from_counts, including its strict threshold
 * and FP32 admission arithmetic.  Descriptor boundaries themselves continue
 * to use the FP64 model in the CUDA implementation. */
static inline int dmma_tile_tail_queue_chunk_count(
    const DmmaTileTailQueueExactTask &task,
    const DmmaTileTailQueuePolicy &policy,
    const DmmaTileTailQueueCostModel &model)
{
    const float work = static_cast<float>(model.scan) *
                           static_cast<float>(task.scans) +
                       static_cast<float>(model.match) *
                           static_cast<float>(task.matches);
    if (!(work > static_cast<float>(policy.admission_threshold)) ||
        task.scans <= 1)
        return 0;
    const float requested =
        std::ceil(work / static_cast<float>(policy.chunk_target));
    int chunks = requested >= static_cast<float>(policy.max_chunks)
                     ? policy.max_chunks
                     : static_cast<int>(requested);
    if (chunks < 2)
        chunks = 2;
    if (chunks > task.scans)
        chunks = task.scans;
    return chunks >= 2 ? chunks : 0;
}

static inline bool dmma_tile_tail_queue_checked_mul(
    std::size_t left, std::size_t right, std::size_t *result)
{
    if (result == nullptr ||
        (left != 0 && right > std::numeric_limits<std::size_t>::max() / left))
        return false;
    *result = left * right;
    return true;
}

/* Descriptor bytes use the production ABI (four 32-bit fields).  A workspace
 * chunk owns one dense 8x8 FP64 partial accumulator, or 512 bytes. */
static inline DmmaTileTailQueuePlan dmma_plan_tile_tail_queue(
    const std::vector<DmmaTileTailQueueExactTask> &tasks,
    const DmmaTileTailQueuePolicy &policy,
    const DmmaTileTailQueueCostModel &model)
{
    DmmaTileTailQueuePlan plan;
    plan.output_tasks = tasks.size();
    plan.ordinary_tasks = tasks.size();
    if (!policy.enabled)
        return plan;
    if (!dmma_tile_tail_queue_policy_valid(policy, model))
    {
        plan.reason = DMMA_TILE_TAIL_QUEUE_INVALID_POLICY;
        return plan;
    }

    plan.heavy.reserve(tasks.size() < static_cast<std::size_t>(
                                         policy.record_capacity)
                           ? tasks.size()
                           : static_cast<std::size_t>(policy.record_capacity));
    for (std::size_t index = 0; index < tasks.size(); ++index)
    {
        const DmmaTileTailQueueExactTask &task = tasks[index];
        if (task.task != static_cast<int>(index) || task.scans < 0 ||
            task.matches < 0 ||
            task.matches > task.scans || task.output_nnz < 0 ||
            task.output_nnz > 64)
        {
            plan.reason = DMMA_TILE_TAIL_QUEUE_INVALID_TASK;
            dmma_tile_tail_queue_reset_incomplete_plan(&plan);
            return plan;
        }
        const int chunks =
            dmma_tile_tail_queue_chunk_count(task, policy, model);
        if (chunks == 0)
            continue;
        if (plan.heavy.size() >=
            static_cast<std::size_t>(policy.record_capacity))
        {
            plan.reason = DMMA_TILE_TAIL_QUEUE_RECORD_CAPACITY;
            dmma_tile_tail_queue_reset_incomplete_plan(&plan);
            return plan;
        }
        if (plan.chunks > std::numeric_limits<std::size_t>::max() -
                              static_cast<std::size_t>(chunks))
        {
            plan.reason = DMMA_TILE_TAIL_QUEUE_CHUNK_OVERFLOW;
            dmma_tile_tail_queue_reset_incomplete_plan(&plan);
            return plan;
        }
        DmmaTileTailQueueTaskPlan admitted;
        admitted.task = task.task;
        admitted.scans = task.scans;
        admitted.matches = task.matches;
        admitted.output_nnz = task.output_nnz;
        admitted.chunks = chunks;
        admitted.splittable_work = model.scan * task.scans +
                                   model.match * task.matches;
        admitted.full_work = model.intercept + admitted.splittable_work +
                             model.output * task.output_nnz;
        plan.heavy.push_back(admitted);
        plan.chunks += static_cast<std::size_t>(chunks);
    }

    plan.heavy_tasks = plan.heavy.size();
    plan.ordinary_tasks = plan.output_tasks - plan.heavy_tasks;
    plan.heavy_fraction = plan.output_tasks == 0
                              ? 0.0
                              : static_cast<double>(plan.heavy_tasks) /
                                    static_cast<double>(plan.output_tasks);
    plan.average_chunks = plan.heavy_tasks == 0
                              ? 0.0
                              : static_cast<double>(plan.chunks) /
                                    static_cast<double>(plan.heavy_tasks);
    plan.heavy_flag_bytes = ((plan.output_tasks + 31u) / 32u) * 4u;
    if (!dmma_tile_tail_queue_checked_mul(plan.chunks, 16u,
                                          &plan.descriptor_bytes) ||
        !dmma_tile_tail_queue_checked_mul(plan.chunks, 64u * sizeof(double),
                                          &plan.partial_workspace_bytes))
    {
        plan.reason = DMMA_TILE_TAIL_QUEUE_CHUNK_OVERFLOW;
        dmma_tile_tail_queue_reset_incomplete_plan(&plan);
        return plan;
    }
    if (plan.heavy_tasks == 0)
    {
        plan.reason = DMMA_TILE_TAIL_QUEUE_ZERO_HEAVY;
        return plan;
    }
    if (plan.heavy_fraction > policy.max_heavy_fraction)
    {
        plan.reason = DMMA_TILE_TAIL_QUEUE_HEAVY_FRACTION;
        return plan;
    }
    if (policy.workspace_reduction &&
        plan.partial_workspace_bytes > policy.workspace_limit_bytes)
    {
        plan.reason = DMMA_TILE_TAIL_QUEUE_WORKSPACE_CAPACITY;
        return plan;
    }
    plan.reason = DMMA_TILE_TAIL_QUEUE_ENABLED;
    return plan;
}

#endif
